'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sourceLink=k=>SOURCES[k]?`<a class="source" href="${SOURCES[k][1]}" target="_blank" rel="noopener noreferrer">${esc(SOURCES[k][0])} ↗</a>`:'';
const number=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:1});
const defaultStore={prices:{},owned:[],learned:[],notes:[]};
let localOK=true, saved;
try{saved={...defaultStore,...JSON.parse(localStorage.getItem('taste-atlas-v1')||'{}')};}catch{saved={...defaultStore};localOK=false;}
if(!Array.isArray(saved.owned))saved.owned=[];if(!Array.isArray(saved.learned))saved.learned=[];if(!Array.isArray(saved.notes))saved.notes=[];if(!saved.prices||typeof saved.prices!=='object')saved.prices={};
const state={tab:'beer',section:'map',filter:'favorites',query:'',compare:[],cask:0,quiz:0,answers:{},phase:0};
const MENUS={beer:[['map','전체 스타일 지도'],['history','역사와 갈림길'],['basics','만드는 법 · 읽는 법'],['practice','비교 시음 코스'],['quiz','복습 퀴즈']],whisky:[['map','위스키 지도'],['history','역사 · 계보 · 생산자'],['casks','캐스크 탐구'],['regions','지역과 증류소'],['practice','비교 시음 코스']],cabinet:[['shelf','24병 술장'],['budget','구매 계획표'],['fridge','맥주 냉장고'],['setup','공간과 운영']],notebook:[['notes','나의 시음 기록']],sources:[['sources','출처와 편집 노트'],['archive','대화 · 첨부 전체 원문']]};
function persist(){try{localStorage.setItem('taste-atlas-v1',JSON.stringify(saved));localOK=true;}catch{localOK=false;toast('브라우저가 저장을 허용하지 않습니다. 기록을 내보내 주세요.');}}
let toastTimer;function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2700);}
function price(w){const v=saved.prices[w.id];return Number.isFinite(v)&&v>=0?v:w.price;}
function total(){return WHISKIES.reduce((sum,w)=>sum+price(w),0);}
function readRoute(){const [tab,section]=location.hash.slice(1).split('/');if(MENUS[tab]){state.tab=tab;state.section=MENUS[tab].some(a=>a[0]===section)?section:MENUS[tab][0][0];}else{state.tab='beer';state.section='map';}}
function navigate(tab,section){if(!MENUS[tab])return;const route=`${tab}/${section||MENUS[tab][0][0]}`;if(location.hash==='#'+route)return;rememberPageView();viewCaptured=true;location.hash=route;}
window.addEventListener('hashchange',restoreRoute);
function render(){
 document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===state.tab);if(b.dataset.tab===state.tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 $('.workspace').dataset.page=state.tab;
 renderNav();renderSide();
 const tab=state.tab, section=state.section;
 let html='';
 if(tab==='beer')html=section==='history'?historyPage('beer'):section==='basics'?beerBasics():section==='practice'?practicePage('beer'):section==='quiz'?quizPage():beerMap();
 else if(tab==='whisky')html=section==='history'?whiskyHistoryPage():section==='casks'?caskPage():section==='regions'?regionsPage():section==='practice'?practicePage('whisky'):whiskyMap();
 else if(tab==='cabinet')html=section==='budget'?budgetPage():section==='fridge'?fridgePage():section==='setup'?setupPage():shelfPage();
 else if(tab==='notebook')html=notebookPage();
 else html=section==='archive'?archivePage():sourcesPage();
 $('#main').innerHTML=html;enhancePage();renderCompareBar();
 document.title=`${{beer:'맥주',whisky:'위스키',cabinet:'나의 술장',notebook:'시음 노트',sources:'출처'}[tab]} — 잔의 지도`;
}
function renderNav(){
 const study=['beer','whisky'].includes(state.tab),lessons=state.tab==='whisky'?ALL_WHISKY_LESSONS:BEER_LESSONS;
 const done=lessons.filter(l=>saved.learned.includes(l.id)).length;
 $('#leftnav').innerHTML=`<div class="nav-inner"><nav class="sidenav" aria-label="${study?'학습':'페이지'} 목차">${MENUS[state.tab].map(([s,t],i)=>`<button data-section="${s}" class="${s===state.section?'active':''}" ${s===state.section?'aria-current="page"':''}><span>${String(i+1).padStart(2,'0')}</span>${t}</button>`).join('')}</nav><label class="section-picker"><span>${study?'학습 목차':'바로가기'}</span><select id="section-select" aria-label="${study?'학습 목차':'페이지'} 선택">${MENUS[state.tab].map(([s,t],i)=>`<option value="${s}" ${s===state.section?'selected':''}>${String(i+1).padStart(2,'0')} · ${t}</option>`).join('')}</select></label>${study?`<div class="reading"><span>${state.tab==='beer'?'맥주':'위스키'} 읽은 챕터</span><span>${done} / ${lessons.length}</span><div class="meter" aria-hidden="true"><i style="width:${done/lessons.length*100}%"></i></div></div>`:''}</div>`;
 const active=$('.sidenav .active');if(active)active.parentElement.scrollLeft=Math.max(0,active.offsetLeft-active.parentElement.offsetLeft-14);
}
function renderSide(){
 const side=$('#rightbar');side.hidden=!['beer','whisky'].includes(state.tab);if(side.hidden){side.innerHTML='';return;}
 const t=total();side.innerHTML=`<div class="right-inner"><div class="shelfcard"><span class="eyebrow">YOUR TASTE, CURATED</span><h2>배운 취향을,<br>나의 술장으로.</h2><p>정제된 피트, 서로 다른 캐스크.<br>신선한 라거와 깊은 배럴 맥주.</p><div class="minishelf" aria-hidden="true">${WHISKIES.slice(0,6).map(w=>`<i class="mini-bottle" style="--bottle:${GROUP_COLORS[w.group]}"></i>`).join('')}</div><div class="shelf-numbers"><div><b>24</b><small>위스키 셀렉션</small></div><div><b>600<small style="display:inline;margin-left:3px">만 원</small></b><small>위스키 예산</small></div></div><p class="side-budget">계획 ${number(t)}만 원 · ${t<=600?'여유 '+number(600-t):'초과 '+number(t-600)}만 원</p><button class="action" data-go="cabinet/shelf">24병 구성 보기 ↗</button><button class="side-link" data-go="cabinet/budget">구매 금액·보유 병 관리 ↗</button></div><div class="side-module"><span class="eyebrow">THE COLD SIDE</span><h3>맥주 냉장고 · 44개 + 여유</h3><p>라거부터 배럴 맥주까지.<br>4℃ 보관을 기준으로, 따를 때 온도 조절.</p><button class="side-link" data-go="cabinet/fridge">맥주 구성과 선반 배분 ↗</button></div><div class="side-module"><h3>맥주와 위스키 사이</h3><p>헬레스 ↔ Deanston<br>BA 스타우트 ↔ 버번</p><button class="side-link" data-go="whisky/casks">통에서 연결되는 이야기 ↗</button></div><p class="bullet-note">금액은 구매 목표액이며,<br>맥주·냉장고 비용은 별도입니다.</p></div>`;
}
function topLine(text,num='01'){return `<div class="main-topline"><span class="eyebrow">${num} / ${text}</span><span class="edition">A study in taste</span></div>`;}
function titlePage(eyebrow,title,lead){return `${topLine(eyebrow)}<div class="titlepage"><h1>${title}</h1><p class="lead">${lead}</p></div>`;}
function hero(type){return `<section class="hero"><div class="hero-copy"><span class="eyebrow">${type==='beer'?'GRAIN, FERMENTATION & TIME':'SPIRIT, WOOD & TIME'}</span><h1>${type==='beer'?'맥주는 하나의 역사로<br>흐르지 않는다.':'원액의 성격 위에,<br>시간의 결이 쌓인다.'}</h1><p>${type==='beer'?'맥주가 갈라져 온 역사, 양조장의 선택,<br>그리고 내 취향을 연결하는 학습 지도.':'증류와 숙성이 만든 차이를 읽고,<br>나의 24병에 각자의 이유를 붙여보세요.'}</p><button class="hero-start" data-go="${type}/history">역사에서 시작하기 <span>⟶</span></button></div><div class="hero-art" aria-hidden="true"><div class="circle"><i class="glass" style="--drink:#d3b45d"><span class="glass-label">${type==='beer'?'MALT':'GRAIN'}</span></i><i class="glass" style="--drink:#ad783e"><span class="glass-label">${type==='beer'?'HOPS':'WOOD'}</span></i><i class="glass" style="--drink:#50382b"><span class="glass-label">TIME</span></i></div><small>Three glasses. A wider world.</small></div></section>`;}
function filterUI(groups){return `<div class="filters" aria-label="분류 선택">${Object.entries(groups).map(([k,v])=>`<button class="chip ${state.filter===k&&!state.query.trim()?'active':''}" data-filter="${k}" aria-pressed="${state.filter===k&&!state.query.trim()}">${v}</button>`).join('')}</div><label class="searchwrap"><span aria-hidden="true">⌕</span><input type="search" id="search" value="${esc(state.query)}" placeholder="${state.tab==='beer'?'스타일·양조장·향, 전체 42종에서 검색':'이름·캐스크·향, 전체 24병에서 검색'}" aria-label="스타일, 제품, 향 검색"></label><div class="results-meta"><span id="result-count" role="status" aria-live="polite"></span><button class="textbutton" data-action="clear-search" ${state.query?'':'hidden'}>검색 지우기 ×</button></div>`;}
function beerCard(b){return `<button class="stylecard" data-beer="${b.id}"><span class="card-top"><span class="family">${esc(BEER_GROUPS[b.group])}</span><span class="beer-dot" style="--drink:${b.color}"></span></span><h3>${esc(b.name)}</h3><span class="en">${esc(b.en)}</span><p>${esc(b.desc)}</p><span class="card-bottom"><span>${esc(b.abv)}</span>${b.favorite?'<span class="tag">관심 축</span>':''}<span class="card-arrow">↗</span></span></button>`;}
function filteredBeers(){const q=state.query.toLowerCase().trim();return BEERS.filter(b=>(q||state.filter==='all'||(state.filter==='favorites'?b.favorite:b.group===state.filter))&&(!q||[b.name,b.en,b.examples,b.desc,b.history].join(' ').toLowerCase().includes(q)));}
function beerResults(){const bs=filteredBeers();return bs.length?bs.map(beerCard).join(''):'<p class="empty">일치하는 맥주가 없어요. 다른 분류나 검색어를 골라보세요.</p>';}
function beerMap(){if(!BEER_GROUPS[state.filter])state.filter='favorites';return `${topLine('THE BEER ATLAS')}${hero('beer')}<div class="two-col"><button class="mini-card" style="text-align:left" data-go="beer/history"><span class="eyebrow">START WITH THE STORY</span><h3>스타일마다 다른 역사가 있다 ↗</h3><p>라거, 포터·스타우트, 홉, 벨기에.<br>12개 챕터로 분화의 이유부터 읽기.</p></button><button class="mini-card" style="text-align:left" data-go="beer/practice"><span class="eyebrow">LEARN BY COMPARING</span><h3>두 잔 사이에서 배우기 ↗</h3><p>이름을 외운 뒤가 아니라,<br>차이를 묻는 순간부터 시작하는 학습.</p></button></div><div class="sectionline"><div><h2>스타일을 펼쳐보다</h2><p>카드를 열면 역사·대표 제품·비교 질문이 이어집니다.</p></div><small>${BEERS.length} study cards</small></div>${filterUI(BEER_GROUPS)}<div class="stylegrid" id="results">${beerResults()}</div><div class="callout">지도는 학습용 묶음입니다. 일부 카드는 가까운 스타일을 함께 다루고, 산미·배럴처럼 기본 스타일과 겹치는 축도 따로 보여줍니다. 도수 범위는 길잡이이며 제품 규격은 아닙니다.</div>`;}
function bars(profile,kind='beer'){const labels=kind==='beer'?['몰트','홉','로스트','산미','몸체']:['과실','연기','단향','오크','몸체'];return `<div class="bars">${profile.map((v,i)=>`<div class="bar-row"><span>${labels[i]}</span><div class="track"><i style="width:${v*20}%"></i></div><b>${v}</b></div>`).join('')}</div><p class="fine">0–5 상대 강도는 학습을 돕는 편집상 인상입니다. 측정값·품질 점수가 아닙니다.</p>`;}
function openDialog(html){$('#detail-body').innerHTML=html;$('#detail').setAttribute('aria-label',$('#detail-body h2')?.textContent||'제품 상세와 비교');if(!$('#detail').open)$('#detail').showModal();document.body.classList.add('dialog-open');$('#detail').scrollTop=0;}
function openBeer(id){const b=BEERS.find(x=>x.id===id);if(!b)return;openDialog(`<div class="modalhead"><span class="beer-dot" style="--drink:${b.color}"></span><div><span class="eyebrow">${BEER_GROUPS[b.group]} · ${esc(b.abv)}</span><h2>${esc(b.name)}</h2><span class="en">${esc(b.en)}</span></div></div><p class="detail-intro">${esc(b.desc)}</p>${bars(b.profile)}<div class="detail-grid"><div><h4>어디에서 갈라졌을까</h4><p>${esc(b.history)}</p></div><div><h4>이름을 기억할 기준점</h4><p>${esc(b.examples)}</p></div></div><div class="callout"><strong>이 잔의 질문</strong><br>${esc(b.question)}</div>${sourceLink(b.source)}<div class="modal-actions"><button class="action" data-compare="${b.id}">${state.compare.includes(b.id)?'비교에서 빼기':'다른 스타일과 비교'}</button><button class="action secondary" data-note-name="${esc(b.name)}" data-note-kind="맥주">시음 기록하기</button><button class="textbutton" data-go="beer/history">전체 역사 읽기 ↗</button></div>`);}
function renderCompareBar(){const bar=$('#compare-bar');bar.hidden=!state.compare.length||state.tab!=='beer';if(state.compare.length)bar.innerHTML=`<span>${state.compare.map(id=>BEERS.find(b=>b.id===id)?.name).join(' · ')}</span><button class="action" data-action="compare-open" ${state.compare.length<2?'disabled':''}>${state.compare.length}종 비교</button><button data-action="compare-clear" aria-label="비교 선택 비우기">×</button>`;}
function openCompare(){const bs=state.compare.map(id=>BEERS.find(b=>b.id===id));openDialog(`<span class="eyebrow">SIDE BY SIDE</span><h2 style="margin:12px 0 20px">차이를 나란히 놓다</h2><div class="table-scroll"><table class="compare-table"><thead><tr><th>비교점</th>${bs.map(b=>`<th>${esc(b.name)}</th>`).join('')}</tr></thead><tbody>${[['중심 표현','desc'],['발효·역사','history'],['참고 도수','abv'],['대표 제품','examples'],['시음 질문','question']].map(([label,key])=>`<tr><td>${label}</td>${bs.map(b=>`<td>${esc(b[key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="fine" style="margin-top:16px">맛의 비교이지 실제 출시 순서나 우열의 비교가 아닙니다.</p>`);}
function lessonHTML(l,i){return `<details class="lesson" id="${l.id}"><summary><span class="lesson-number">${String(i+1).padStart(2,'0')}</span><span><h3>${l.title}</h3><p>${l.sub}</p></span></summary><div class="lesson-body">${l.body}<div style="display:flex;gap:12px;flex-wrap:wrap">${l.source.map(sourceLink).join('')}</div><label class="checklearn"><input type="checkbox" data-learn="${l.id}" ${saved.learned.includes(l.id)?'checked':''}>이 챕터를 읽었어요</label></div></details>`;}
function historyPage(kind){const beer=kind==='beer';const ls=beer?BEER_LESSONS:WHISKY_LESSONS;return `${titlePage(beer?'HISTORY & BRANCHES':'HISTORY & GRAMMAR',beer?'맥주는 여러 역사로 흐른다.':'위스키를 만드는 선택들.',beer?'지역의 재료, 새로운 기술, 마시는 문화가 만나 각자의 스타일을 만들었습니다. 앞선 대화의 모든 주제를 유지하며 맥락과 구별할 점을 보강했습니다.':'증류기의 선택부터 블렌딩까지. 지역 이름과 연수 뒤에 있는 만드는 방법을 먼저 읽습니다.')}<div class="sectionline"><p class="fine">${ls.length}개 챕터 · 제목을 눌러 읽기</p><button class="textbutton" data-action="expand-lessons">모두 펼치기</button></div>${ls.map(lessonHTML).join('')}<div class="callout">원문에 나온 모든 세부 사례·변형 제품·이전 가격은 <button class="textbutton" data-go="sources/archive">이전 대화 전체 원문</button>에도 그대로 보존했습니다. 본문의 보완 설명과 함께 대조할 수 있습니다.</div>`;}
function beerBasics(){return `${titlePage('FROM GRAIN TO GLASS','맛은 어디에서 올까.','향을 맞히기보다 그 향을 만든 선택을 이해하는 쪽으로.')}<div class="process">${[['01','몰트','전분과 효소. 건조·로스팅으로 빵·토스트·커피 방향을 만든다.'],['02','당화 · 끓임','전분을 당으로 전환하고 맥즙을 끓인다. 홉 투입 시점은 향과 쓴맛에 영향을 준다.'],['03','발효','효모가 당을 알코올·탄산과 여러 향 성분으로 바꾼다. 균주와 온도를 읽는다.'],['04','숙성 · 포장','시간·통·탄산·산소 관리가 최종 결과를 바꾼다. 유통 신선도까지가 경험의 일부.']].map(([n,t,p])=>`<div><b>${n}</b><h4>${t}</h4><p>${p}</p></div>`).join('')}</div>${lessonHTML(BEER_LESSONS[0],0)}${lessonHTML(BEER_LESSONS[11],11)}<div class="contentblock"><h3>라벨에서 먼저 찾을 다섯 가지</h3><p>기본 스타일 → ABV(알코올 도수) → 포장·병입일 → 배럴·추가 재료 → 보관 안내. IBU는 참고 지표로 읽고 실제 체감 쓴맛과 따로 기록하세요.</p><p>예를 들어 “Bourbon Barrel-Aged Imperial Stout with Vanilla”는 임페리얼 스타우트를 버번통에서 숙성하고 바닐라를 더했다는 설명입니다. 바닐라를 넣지 않은 BA에서도 비슷한 향이 날 수 있습니다.</p></div><div class="rangecontrol"><label for="serve-temp">온도가 바뀌면 무엇을 볼까 <strong id="temp-label">8℃</strong></label><input id="serve-temp" type="range" min="3" max="16" value="8"><p id="temp-explain" class="fine">차가운 라거에서 시작해 조금 더 열린 몰트·홉 향을 관찰하는 구간입니다.</p></div>`;}
function whiskyCard(w){return `<button class="stylecard" data-whisky="${w.id}"><span class="card-top"><span class="family">${WHISKY_GROUPS[w.group]}</span><span class="beer-dot" style="--drink:${GROUP_COLORS[w.group]}"></span></span><h3>${esc(w.ko)}</h3><span class="en">${esc(w.name)}</span><p>${esc(w.notes)}</p><span class="card-bottom"><span>${esc(w.abv)}</span><span>술장 ${String(w.id).padStart(2,'0')} ↗</span></span></button>`;}
function filteredWhiskies(){const q=state.query.toLowerCase().trim();return WHISKIES.filter(w=>(q||state.filter==='all'||state.filter===w.group)&&(!q||[w.name,w.ko,w.notes,w.cask,w.why].join(' ').toLowerCase().includes(q)));}
function whiskyResults(){const ws=filteredWhiskies();return ws.length?ws.map(whiskyCard).join(''):'<p class="empty">일치하는 병이 없어요. 다른 분류나 검색어를 골라보세요.</p>';}
function whiskyMap(){if(!WHISKY_GROUPS[state.filter])state.filter='all';return `${topLine('THE WHISKY ATLAS','02')}${hero('whisky')}<div class="two-col"><button class="mini-card" style="text-align:left" data-go="whisky/history"><span class="eyebrow">READ THE LABEL</span><h3>근본부터 세계의 생산자까지 ↗</h3><p>곡물·증류소·통·연수·병입의 문법.<br>13개 본문 + 8개 보충 학습으로<br>역사·계보·대표 생산자를 연결합니다.</p></button><button class="mini-card" style="text-align:left" data-go="whisky/casks"><span class="eyebrow">FOLLOW THE WOOD</span><h3>버번통, 셰리통, 그리고 와인 ↗</h3><p>같은 증류주에 다른 통이 남기는 것.<br>맥주와 연결해서 관찰해보세요.</p></button></div><div class="sectionline"><div><h2>취향을 여는 24개의 기준점</h2><p>각 병은 하나의 비교 질문을 맡습니다.</p></div><small>24 expressions</small></div>${filterUI(WHISKY_GROUPS)}<div class="stylegrid" id="results">${whiskyResults()}</div><div class="callout">풍미는 제조사 설명과 편집상 비교 관점입니다. 개인의 감각과 병·배치·보관에 따라 다르게 느껴질 수 있습니다.</div>`;}
function openWhisky(id){const w=WHISKIES.find(x=>x.id===Number(id));if(!w)return;openDialog(`<div class="modalhead"><div class="mini-bottle" style="--bottle:${GROUP_COLORS[w.group]};margin:15px"></div><div><span class="eyebrow">SHELF ${String(w.id).padStart(2,'0')} · ${WHISKY_GROUPS[w.group]}</span><h2>${esc(w.ko)}</h2><span class="en">${esc(w.name)}</span></div></div><p class="detail-intro">${esc(w.notes)}</p><p class="fine">${esc(w.cask)} · ${esc(w.abv)}</p>${bars(w.profile,'whisky')}<div class="detail-grid"><div><h4>왜 이 술장에 넣었을까</h4><p>${esc(w.why)}</p></div><div><h4>이 선택의 약점</h4><p>${esc(w.caution)}</p></div></div><div class="callout"><strong>같은 자리의 대안</strong><br>${esc(w.alt)}<br><span class="fine">대안은 현재 합계에 포함되지 않습니다. 교체 시 별도 가격·재고 확인이 필요합니다.</span></div><p>구매 목표액 <strong>${number(price(w))}만 원</strong> <span class="fine">· ${w.phase}차 구매</span></p>${sourceLink(w.source)}<div class="modal-actions"><button class="action" data-note-name="${esc(w.ko)}" data-note-kind="위스키">시음 기록하기</button><button class="action secondary" data-owned="${w.id}">${saved.owned.includes(w.id)?'보유 체크 해제':'보유 병으로 체크'}</button><button class="textbutton" data-go="cabinet/budget">계획 금액 수정 ↗</button></div>`);}
function baseCaskPage(){return `${titlePage('THE LIFE OF A CASK','통에도 이력이 있다.','곡물의 발효에서 시작한 두 술이, 오크통에서 다시 만납니다.')}<div class="route"><span>버번 · 새 오크</span><i>→ 일부 통</i><span>스카치 등 재사용</span><i>→ 일부 통</i><span>맥주 숙성</span></div><p class="fine">실제 통의 이동 경로는 제각각입니다. 버번통이 바로 맥주로 가기도 합니다.</p><div class="cask-tabs" role="group" aria-label="캐스크 선택">${CASKS.map((c,i)=>`<button class="chip ${i===state.cask?'active':''}" data-cask="${i}" aria-pressed="${i===state.cask}">${c.name}</button>`).join('')}</div><div id="cask-panel">${caskPanel()}</div>${lessonHTML(WHISKY_LESSONS[4],4)}<div class="contentblock"><h3>같이 배우면 선명해지는 세 가지</h3><p><strong>헬레스 ↔ 원액 중심 몰트</strong> — 빵·곡물에 주의를 기울이는 관찰 습관을 옮겨보기.</p><p><strong>BA 스타우트 ↔ 버번</strong> — 로스트와 통의 바닐라·오크를 나눠보기.</p><p><strong>라우흐비어 ↔ 피트 위스키</strong> — 곡물 건조에 쓰인 연기와 이후 제조 과정의 차이 보기.</p><p class="fine">이는 비교 학습 제안이며 동일한 향미나 선호를 보장하지 않습니다.</p></div>`;}
function caskPanel(){const c=CASKS[state.cask];return `<article class="caskpanel"><span class="eyebrow">${c.en}</span><h3 style="margin-top:9px">${c.name}</h3><p>${c.text}</p><p style="margin-top:15px"><strong>${c.pair}</strong></p><p class="fine" style="margin-top:10px">${c.note}</p>${sourceLink(c.source)}</article>`;}
function baseRegionsPage(){return `${titlePage('PLACES & PEOPLE','지역을 읽고, 원액을 만나다.','지역은 질문을 시작하는 힌트입니다. 실제 맛은 증류소와 병마다 달라집니다.')}<div class="two-col">${[['Highland / Islands','Deanston · Clynelish · Talisker · Highland Park','범위가 넓고 몰트·왁스·해안·피트가 공존. Islands는 흔한 묶음이지만 법적 독립 지역 분류와 구분.'],['Speyside','Macallan · GlenAllachie · Benromach','셰리 몰트만의 땅이 아니다. Benromach의 스모크 같은 예외를 함께 보자.'],['Islay','Caol Ila · Bowmore','연기·해안·과실의 결합을 비교하되 무피트 생산도 있다는 점을 기억.'],['Campbeltown','Kilkerran · Springbank','오일·몰트·약한 연기·복합적인 발효 인상 등 원액의 촉감을 비교.'],['Lowland','Auchentoshan · Bladnoch','섬세한 원액을 탐색할 지역. 모든 로우랜드가 가볍거나 세 번 증류하는 것은 아니다.'],['Beyond Scotland','Redbreast · Kavalan · Hakushu · Ki One','곡물·증류·기후·숙성의 조건을 하나씩 더 넓혀 읽기.']].map(([name,ex,desc])=>`<article class="mini-card"><span class="eyebrow">${name}</span><h3>${ex}</h3><p>${desc}</p></article>`).join('')}</div>${lessonHTML(WHISKY_LESSONS[5],5)}${sourceLink('swa')}`;}
function practicePage(kind){const beer=kind==='beer',flights=beer?BEER_FLIGHTS:WHISKY_FLIGHTS;return `${titlePage('TASTING, WITH A QUESTION','외우기보다, 나란히 맛보기.','한 번에 하나의 차이만 묻습니다. 아래 화살표는 비교 시음 순서이며 실제 역사적 계보가 아닙니다.')}<div class="callout">${beer?'맥주 2–3종을 조금씩 나누어 비교하고, 고도수·강한 산미는 별도 날로 나눕니다.':'위스키 2–3병을 각각 10–15ml 정도로 비교하는 계획부터 시작하세요. 같은 잔과 기록 방식이 도움이 됩니다.'}</div>${flights.map((f,i)=>`<article class="contentblock"><span class="eyebrow">FLIGHT ${String(i+1).padStart(2,'0')}</span><h3 style="margin-top:8px">${f[0]}</h3><div class="route">${f[1].split(/ → | ↔ /).map(x=>`<span>${esc(x)}</span>`).join('<i>↔</i>')}</div><p>${f[2]}</p>${f[3]?`<p class="fine">${f[3]}</p>`:''}<button class="textbutton" data-note-name="${esc(f[0])}" data-note-kind="${beer?'맥주':'위스키'}">이 비교를 기록하기 ↗</button></article>`).join('')}<button class="action" data-go="notebook/notes">시음 노트 열기 ↗</button>`;}
function shelfBottle(w){return `<button class="bottle-slot ${saved.owned.includes(w.id)?'owned':''}" data-whisky="${w.id}" aria-label="${esc(w.ko)} 상세 보기"><span class="slotnum">${String(w.id).padStart(2,'0')}</span><div class="bottle" style="--bottle:${GROUP_COLORS[w.group]}" data-mark="${String(w.name.match(/\d+/)?.[0]||'–')}" aria-hidden="true"></div><small>${esc(w.ko.replace('캐스크','').replace('싱글 몰트',''))}</small></button>`;}
function budgetStats(){const t=total();return `<div class="budget-stats"><div><small>위스키 예산</small><strong>600<small style="display:inline"> 만 원</small></strong></div><div><small>24병 구매 계획액</small><strong>${number(t)}<small style="display:inline"> 만 원</small></strong></div><div><small>${t<=600?'남겨둔 여유':'예산 초과'}</small><strong class="${t>600?'over':''}">${number(Math.abs(600-t))}<small style="display:inline"> 만 원</small></strong></div></div><div class="meter" style="margin-top:14px"><i style="width:${Math.min(100,t/600*100)}%;${t>600?'background:#a4513c':''}"></i></div>`;}
function shelfPage(){return `${titlePage('A CABINET WITH CHARACTER','24병, 각자의 자리가 있다.','기존 대화의 섬세한 피트·셰리·와인·그레인을 중심에 두고, 곡물과 원액의 질감을 배우는 병을 더했습니다.')}<div class="shelf-overview">${budgetStats()}<div class="shelf-grid">${WHISKIES.map(shelfBottle).join('')}</div><div class="legend">${Object.entries(GROUP_COLORS).map(([g,c])=>`<span><i style="--bottle:${c}"></i>${WHISKY_GROUPS[g]} ${WHISKIES.filter(w=>w.group===g).length}</span>`).join('')}</div><p class="fine">병 모양은 배치를 보여주는 도식입니다. 실제 제품 이미지가 아닙니다. 병을 누르면 선정 이유·약점·대안을 볼 수 있습니다.</p></div><div class="two-col"><article class="mini-card"><span class="eyebrow">THE HOST’S CHARACTER</span><h3>숙성의 표정을 비교하는 사람</h3><p>연기의 세기보다 다른 재료와 엮이는 방식, 셰리의 진함보다 통마다 다른 표현에 관심을 둔 술장. 명성 높은 한 병과 작은 실험의 병이 함께 있습니다.</p></article><article class="mini-card"><span class="eyebrow">ROOM TO CHANGE</span><h3>한 번에 24병을 사지 않기</h3><p>먼저 기준점 ${WHISKIES.filter(w=>w.phase===1).length}병을 고르고 시음한 뒤 확장하세요. 24병이라는 수보다 각 병이 새로 알려주는 차이가 더 중요합니다.</p></article></div><div class="sectionline"><h2>이 구성의 선택과 약점</h2></div><div class="contentblock"><h3>기존 12병에서 무엇을 넓혔나</h3><p>4개 피트 중심을 6개로, 셰리·와인 3개를 5개로 확장했습니다. 미국 곡물 비교 4병, 원액·질감 2병, 블렌딩 2병, 아일랜드·일본·대만·한국 5병을 배치했습니다. 이 분류는 구매 역할이며, 일본 병의 피트처럼 향미 축은 겹칩니다.</p><p>기본안은 스카치, 특히 셰리와 연기에 비중이 큽니다. 더 넓은 세계 여행이 목적이면 셰리 병 한두 개를 줄이는 편이 낫고, 지금의 취향을 깊게 배우는 목적이라면 이 중복은 비교 자료가 됩니다.</p><p>Springbank 15는 확인한 국내 판매 사례가 53.9만 원으로 높아 Kilkerran 12를 기본안으로 골랐습니다. 희소성 프리미엄을 감수할 이유가 있는지는 시음 후 결정할 수 있습니다.</p>${sourceLink('springprice')}</div><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="action" data-go="cabinet/budget">24병 가격·구매 순서 보기 ↗</button><button class="action secondary" data-go="cabinet/fridge">옆에 놓을 맥주 냉장고 ↗</button></div>`;}
function budgetPage(){return `${titlePage('THE BUYING PLAN','600만 원을 쓰는 순서.','아래 숫자는 확정 판매가가 아닌 병당 구매 목표액입니다. 실제 견적을 입력하면 합계와 남은 예산이 바뀝니다.')}<div class="shelf-overview" id="budget-summary">${budgetStats()}</div><div class="callout warm">기본 합계 567만 원 + 여유 33만 원. 재고·용량·수입 경로·구형/신형에 따라 목표액을 넘을 수 있습니다. 맥주·냉장고·가구·배송비는 이 600만 원에 포함하지 않았습니다.</div><div class="filters">${[[0,'전체 24병'],[1,'1차 · 기준점'],[2,'2차 · 대조'],[3,'3차 · 확장']].map(([p,t])=>`<button class="chip ${state.phase===p?'active':''}" data-phase="${p}">${t}</button>`).join('')}</div><div class="table-scroll"><table class="price-table"><thead><tr><th>병 · 역할</th><th>목표액 (만 원)</th><th>순서</th><th>보유</th></tr></thead><tbody>${WHISKIES.filter(w=>!state.phase||w.phase===state.phase).map(w=>`<tr><td><button data-whisky="${w.id}">${String(w.id).padStart(2,'0')}. ${esc(w.ko)}</button><small>${WHISKY_GROUPS[w.group]}</small></td><td><input type="number" min="0" max="10000" step="0.1" value="${price(w)}" data-price="${w.id}" aria-label="${esc(w.ko)} 목표액 만 원"></td><td>${w.phase}차</td><td><input type="checkbox" data-owned-check="${w.id}" ${saved.owned.includes(w.id)?'checked':''} aria-label="${esc(w.ko)} 보유"></td></tr>`).join('')}</tbody></table></div><p class="fine" style="margin:12px 0">보유 체크는 재고 표시입니다. 전체 구성의 가치 비교를 위해 합계에서는 빼지 않습니다. 변경 내용은 이 브라우저에 저장됩니다.</p><div class="two-col">${[1,2,3].map(p=>`<article class="mini-card"><span class="eyebrow">PHASE ${p}</span><h3>${p===1?'취향을 잡는 기준점':p===2?'차이를 더하는 비교 병':'여백을 채우는 확장 병'}</h3><p>${WHISKIES.filter(w=>w.phase===p).length}병 · 현재 계획 <span class="phase-total" data-phase-total="${p}">${number(WHISKIES.filter(w=>w.phase===p).reduce((s,w)=>s+price(w),0))}</span>만 원</p></article>`).join('')}</div><div class="contentblock"><h3>가격이 오르면 먼저 바꿀 자리</h3><p>① Hakushu 12 → Distiller’s Reserve: 일본의 허브·연기라는 역할을 남기며 비용 재검토.<br>② Macallan 18 → 12 Sherry Oak 또는 Tamdhu 계열: 명성보다 캐스크 비교가 우선일 때.<br>③ 한정 GlenAllachie·Ki One → 현행 릴리스: 같은 이름으로 취급하지 않고 사양을 새로 기록.</p><p>기존 대화의 다른 선택지인 Ledaig 18, Port Charlotte 18, Tamdhu 18, GlenAllachie Sauternes, Yamazaki 12도 원문에 보존했습니다. 이 대안들의 가격은 현재 합계에 반영되지 않습니다.</p></div><button class="action" data-action="export">계획·기록 내보내기 ↓</button>`;}
const FRIDGE_SHELVES=[
 {name:'01 · 밝은 몰트와 라거',count:'12개',color:'#c7af60',n:12,empty:0,items:'Augustiner Hell 4 · Weihenstephaner Helles 4 · Pilsner Urquell 4',why:'헬레스 두 양조장과 필스너의 비교를 기본 재고로.'},
 {name:'02 · 신선한 홉과 가까운 라거',count:'12개',color:'#8fa06f',n:12,empty:0,items:'Sierra Nevada Pale Ale 2 · Sculpin 2 · 신선한 국내 Hazy IPA 4 · OBC 헬레스 계열 4',why:'홉 맥주는 대량 비축보다 작은 회전. 국내 제품은 해당 출시 스타일 확인.'},
 {name:'03 · 효모, 로스트, 첫 산미',count:'12개',color:'#b18b61',n:12,empty:0,items:'Saison Dupont 2 · Orval 2 · Westmalle Tripel 1 · Rochefort 10 1 · Fuller’s Porter 2 · Old Rasputin 2 · Boon Oude Geuze 2',why:'벨기에·포터·임스·괴즈를 비교하는 작은 학습 선반.'},
 {name:'04 · 배럴과 블렌딩, 여백',count:'8개 + 여유 4칸',color:'#725847',n:8,empty:4,items:'Bourbon County 2 · Parabola 2 · Black Tuesday 1 · Founders KBS 1 · 3 Fonteinen Oude Geuze 1 · Rodenbach Grand Cru 1',why:'큰 병을 여러 개 겹쳐 사기보다 다른 베이스·통·첨가 재료를 경험.'}
];
function fridgePage(){return `${titlePage('THE BEER FRIDGE','차갑게 두고, 넓게 경험하기.','라거 16 · 홉 8 · 벨기에 6 · 다크 4 · BA 6 · 산미 4. 총 44개를 기준으로 네 자리를 비워 두는 구매 구성입니다.')}<div class="fridge"><div class="fridge-top"><span>THE COLD CABINET · 44 + 4</span><strong>4 °C</strong></div>${FRIDGE_SHELVES.map(s=>`<section class="fridge-shelf"><h4>${s.name}<span>${s.count}</span></h4><p>${s.why}</p><div class="cans" aria-hidden="true">${Array.from({length:s.n},()=>`<i class="can" style="--can:${s.color}"></i>`).join('')}${Array.from({length:s.empty},()=>'<i class="can empty-can"></i>').join('')}</div><p style="margin-top:11px;color:#59694d">${s.items}</p></section>`).join('')}</div><div class="callout">이 그림은 재고 배분도입니다. 실제 330ml·500ml·750ml 병의 폭과 높이가 달라 48개의 동일한 물리적 칸을 뜻하지 않습니다. 큰 병이 들어갈 선반 간격·허용 하중·실제 수납 개수를 먼저 확인하세요.</div><div class="two-col"><article class="mini-card"><span class="eyebrow">BUY FRESH</span><h3>앞 두 선반은 회전형</h3><p>IPA·라거는 소비 속도와 생산자 권장 기한에 맞춰 소량 재구매. 포장일·냉장 유통을 확인하고, 오래된 유명 제품보다 신선한 대안을 우선합니다.</p></article><article class="mini-card"><span class="eyebrow">TASTE WITH TIME</span><h3>뒤 두 선반은 비교형</h3><p>BA·람빅도 자동으로 장기 숙성하지 않습니다. 기본은 냉장 보관, 마실 때 온도 조절. 별도 숙성은 적합한 제품과 조건을 정한 뒤 진행합니다.</p></article></div><div class="contentblock"><h3>비용과 더 단순한 시작</h3><p>첫 충전 맥주 비용은 <strong>약 40–65만 원의 계획 범위</strong>로 잡습니다. 이는 검증된 소매 합산이 아니며 BA 빈티지·대형병이 비용을 크게 바꿉니다. 수입 한정품을 찾느라 전부 한 번에 채울 필요는 없습니다.</p><p>더 단순하게 시작하려면 라거 8, IPA 4, 벨기에 3, 다크 2, BA 3, 산미 2의 <strong>22개 반량 구성</strong>이 좋습니다. 같은 학습 범위를 유지하면서 재고와 초기 비용을 줄입니다.</p><p>Black Tuesday를 구하기 어렵다면 검증된 다른 BA Imperial Stout, Parabola가 없으면 첨가 재료가 적은 다른 BA 제품, Sculpin이 오래됐으면 신선한 West Coast IPA를 같은 학습 자리에 둡니다. 취향을 배우는 역할이 브랜드 확보보다 우선입니다.</p>${sourceLink('storage')}</div><button class="action" data-go="cabinet/setup">냉장고·가구 배치와 운영 보기 ↗</button>`;}
function setupPage(){return `${titlePage('THE SPACE AROUND THE BOTTLES','술장이 편해지는 배치.','상온의 위스키 선반과 차가운 맥주 냉장고를 한 공간에 두되, 냉장고 방열과 빛을 고려합니다.')}<div class="two-col"><article class="mini-card"><span class="eyebrow">WHISKY · UPRIGHT</span><h3>4단 × 6병의 위스키 선반</h3><p>자주 쓰는 기준 병을 손이 편한 높이에, 무거운 병은 낮게 배치. 병을 세우고 뒤쪽 병도 꺼내기 쉽게 한 줄이나 얕은 단차로 둡니다. 실제 폭·높이는 병과 가구를 측정해 결정합니다.</p></article><article class="mini-card"><span class="eyebrow">BEER · COLD & DARK</span><h3>하부 또는 옆의 독립 냉장고</h3><p>100–150L급을 탐색 출발점으로 삼되 실제 내부 치수가 우선. 750ml 병을 세울 수 있는 탈착 선반, 3–5℃ 운전 범위, 소음·문 개방·방열 공간을 확인합니다.</p></article></div><div class="contentblock"><h3>장비 선택의 기준</h3><p><strong>우선안:</strong> 온도 조절이 가능한 독립형 음료 냉장고 또는 소형 일반 냉장고. 유리문이면 직사광선을 피하고 빛 차단을 고려합니다. 온도계 하나로 선반별 실제 온도를 측정하세요.</p><p><strong>더 단순한 대안:</strong> 기존 냉장고에 전용 선반을 마련하고 22개 반량 재고로 시작. 소비량을 확인한 뒤 독립 냉장고를 사면 크기·소음에 대한 시행착오를 줄일 수 있습니다.</p><p><strong>약점:</strong> 예쁜 유리문은 빛·가격·소음 측면에서 불리할 수 있고, 일반적인 와인 셀러는 신선한 IPA·라거를 원하는 만큼 차갑게 못 할 수 있습니다. 제조사의 실제 설정 범위와 독립형/빌트인 설치 조건을 확인합니다.</p></div><div class="contentblock"><h3>위스키 600만 원 밖의 계획 예산</h3><p>맥주 첫 충전 40–65만 원 · 냉장고 탐색 예산 30–70만 원 · 잔·온도계·트레이 5–15만 원. <strong>합계 75–150만 원을 별도 여유로</strong> 생각할 수 있습니다. 모델·판매가를 검증한 견적이 아닌 배분용 추정이며 가구·배송·설치는 별도입니다.</p><p>처음에는 튤립잔·작은 위스키 테이스팅 잔을 각각 두 개씩 준비하면 비교가 쉽습니다. 모든 스타일에 전용 잔을 살 필요는 없습니다.</p></div>${lessonHTML(WHISKY_LESSONS[7],7)}<button class="action" data-go="notebook/notes">첫 비교 시음 기록하기 ↗</button>`;}
function notebookPage(){return `${titlePage('YOUR TASTING JOURNAL','한 잔에 하나의 질문.','향 세 단어, 입안의 질감, 다음 비교. 취향을 발견한 순간을 남겨보세요.')}<p class="fine">${localOK?'기록과 구매 계획은 이 브라우저에 자동 저장됩니다. 다른 기기와 동기화되지 않으며 파일 위치·브라우저에 따라 저장 공간이 달라질 수 있습니다.':'브라우저 저장이 제한되어 있습니다. 페이지를 닫기 전에 기록을 내보내세요.'}</p><form id="note-form" class="note-form"><div class="field"><label for="note-name">제품 또는 비교 주제</label><input id="note-name" name="name" required maxlength="160" placeholder="예: 헬레스 두 양조장의 차이"></div><div class="field"><label for="note-kind">종류</label><select id="note-kind" name="kind"><option>맥주</option><option>위스키</option><option>맥주 ↔ 위스키</option></select></div><div class="field"><label for="note-date">시음 날짜</label><input id="note-date" name="date" type="date" required value="${new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10)}"></div><div class="field"><label for="note-batch">빈티지 · 배치 · 병입일</label><input id="note-batch" name="batch" maxlength="160" placeholder="라벨에서 확인한 정보"></div><div class="field full"><label for="note-text">나의 기록</label><textarea id="note-text" name="text" required maxlength="10000" placeholder="향 세 단어 / 질감 / 마무리 / 다음에 비교할 것"></textarea></div><div class="field"><button class="action" type="submit">시음 기록 저장 ＋</button></div></form><div class="sectionline"><h2>남겨둔 기록 <small>${saved.notes.length}</small></h2><button class="textbutton" data-action="export">기록·계획 내보내기 ↓</button></div><div id="saved-notes">${saved.notes.length?saved.notes.map(noteCard).join(''):'<p class="empty">아직 기록이 없어요. 첫 잔에서 발견한 차이를 남겨보세요.</p>'}</div><div class="contentblock"><h3>다른 브라우저로 옮기기</h3><p>내보낸 JSON 기록 파일을 선택하면 현재 기록에 합칩니다. 같은 기록은 중복하지 않고, 파일에 포함된 구매 목표액과 체크 상태를 적용합니다.</p><label class="textbutton" for="import-file" style="cursor:pointer">기록 파일 가져오기 ↑</label><input id="import-file" type="file" accept="application/json,.json" hidden></div>`;}
function noteCard(n){return `<article class="saved-note"><header><div><span class="eyebrow">${esc(n.kind)} · ${esc(n.date)}</span><h3 style="margin-top:7px">${esc(n.name)}</h3></div><span class="fine">${esc(n.batch)}</span></header><p>${esc(n.text)}</p></article>`;}
function exportData(){const data={version:1,exportedAt:new Date().toISOString(),...saved,whiskyPlan:WHISKIES.map(w=>({id:w.id,name:w.name,ko:w.ko,targetPriceManWon:price(w)}))};downloadFile('잔의지도-기록과계획.json',JSON.stringify(data,null,2),'application/json');toast('기록과 계획을 내보냈습니다.');}
function downloadFile(name,text,type){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function quizPage(){const q=QUIZ[state.quiz],chosen=state.answers[state.quiz],done=Object.keys(state.answers).length,score=Object.entries(state.answers).filter(([i,a])=>QUIZ[i][2]===a).length;return `${titlePage('A LITTLE RECALL','이름보다 원리를 기억하기.','스타일·숙성·라벨에서 헷갈리기 쉬운 차이들을 확인해보세요.')}<div class="contentblock"><span class="eyebrow">QUESTION ${state.quiz+1} / ${QUIZ.length}</span><p class="quiz-question">${q[0]}</p><div class="quiz-options">${q[1].map((a,i)=>`<button data-answer="${i}" class="${chosen!==undefined?(i===q[2]?'correct':i===chosen?'wrong':''):''}" ${chosen!==undefined?'disabled':''}>${String.fromCharCode(65+i)}. ${a}</button>`).join('')}</div>${chosen!==undefined?`<div class="quizfeedback"><strong>${chosen===q[2]?'맞았어요.':'다시 살펴볼 점이에요.'}</strong><br>${q[3]}</div>`:''}<div style="display:flex;justify-content:space-between;align-items:center;margin-top:20px"><span class="fine">${done}문항 응답 · ${score}문항 정답</span><button class="action" data-action="quiz-next">${state.quiz===QUIZ.length-1?'처음으로':'다음 질문'} →</button></div></div>`;}
function baseSourcesPage(){return `${titlePage('SOURCES & EDITORIAL NOTES','무엇을 읽고, 무엇을 보완했나.','기존 두 대화와 추가 위스키 첨부 전문을 보존하고, 주요 분류·역사·제품 설명 및 추가 법적 분류·시장 통계를 공개 자료와 대조했습니다. 확인일은 2026년 9월 9일입니다.')}<div class="contentblock"><h3>기존 맥락을 이어받는 방식</h3><p>「맥주 스타일 계보 설명」의 첫 전체 답변, Sculpin 후속 설명, The Bruery 후속 설명과 「위스키 12병 조합 추천」의 요청·답변을 모두 읽었습니다. 원문 전체는 별도 화면에서 열 수 있습니다.</p><p>맥주 본문은 기존 12개 주제와 두 후속 질문을 12개 학습 챕터·스타일 카드·시음 코스로 재배치했습니다. 위스키는 기존 구성 원칙과 교체 후보를 유지하고 600만 원·24병으로 확장했습니다.</p><p>취향은 이 대화에서 요청한 맥락으로 사용했습니다. 기존 답변의 페르소나는 제안된 술장 성격이며 사용자의 고정된 성격에 관한 사실이 아닙니다.</p><button class="action secondary" data-go="sources/archive">대화와 첨부 원문 전체 보기 ↗</button></div><div class="contentblock"><h3>읽으며 보완한 핵심</h3><p>① 역사적 영향 관계와 시음 순서를 분리했습니다. Pliny·Sculpin을 일직선의 출시 계보로 그리지 않습니다.<br>② DIPA는 강도, West Coast·Hazy는 표현 방향, BA는 공정이라는 겹치는 축을 표시했습니다.<br>③ Gose·Berliner Weisse·Brett·Lambic을 모두 같은 야생발효로 묶지 않았습니다.<br>④ ‘최초’·양조장 성격·국가별 비유를 보편적 사실이나 순위로 취급하지 않습니다.<br>⑤ 연수·PPM·CS·가격이 섬세함이나 품질을 보장한다는 인상을 줄였습니다.<br>⑥ 이전 대화의 구형 보모어 18, 한정 Cuvée·기원 배치, 변하는 빈티지 사양과 가격을 현재 정보와 구분했습니다.</p></div><div class="callout warm">모든 병의 국내 판매가·현재 재고를 전수 조사한 구매 견적서는 아닙니다. 제품의 실제 용량·도수·빈티지·판매처를 확인한 뒤 목표액을 수정하세요. 맛 프로필의 0–5 점수와 구매 우선순위는 편집 판단입니다.</div><div class="sectionline"><h2>참고 자료</h2><small>${Object.keys(SOURCES).length} references</small></div><div class="source-list">${Object.entries(SOURCES).map(([id,s])=>`<article class="source-item" id="source-${id}"><a href="${s[1]}" target="_blank" rel="noopener noreferrer">${s[0]} ↗</a><p>${s[2]}</p></article>`).join('')}</div>`;}
function baseArchivePage(){return `${titlePage('THE COMPLETE CONVERSATIONS','이전 대화, 빠짐없이.','조회된 맥주 대화 3회와 위스키 대화 1회의 사용자 요청·답변, 새 위스키 첨부 전문을 보존했습니다. 각 답변을 펼쳐 원문을 읽을 수 있습니다.')}<div class="callout warm">아래는 이전 답변의 보존본입니다. 과거 답변의 가격·출시 사양·단정적인 표현은 새로 검증된 사실로 간주하지 마세요. 원문의 내부 인용 표시는 현재 페이지에서 열리는 링크가 아니며, 위쪽 출처 화면에는 별도로 확인한 자료를 연결했습니다.</div>${ARCHIVE.map((thread,ti)=>`<div class="sectionline"><h2>${esc(thread.title)}</h2><small>${thread.turns.length} turns</small></div>${thread.turns.map((turn,j)=>turn.map((item,k)=>item.role==='사용자'?`<div class="callout"><strong>사용자 요청 ${j+1}</strong><p style="white-space:pre-wrap">${esc(item.text)}</p></div>`:`<details class="lesson"><summary><span class="lesson-number">${String(j+1).padStart(2,'0')}</span><span><h3>이전 답변 전체</h3><p>${number(item.text.length)}자 · 내용 보존</p></span></summary><div class="lesson-body archive-text" data-archive="${ti}-${j}-${k}" style="white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.9;word-break:normal">${esc(item.text)}</div></details>`).join('')).join('')}`).join('')}`;}
function updateBudget(){const el=$('#budget-summary');if(el)el.innerHTML=budgetStats();document.querySelectorAll('[data-phase-total]').forEach(el=>el.textContent=number(WHISKIES.filter(w=>w.phase===+el.dataset.phaseTotal).reduce((s,w)=>s+price(w),0)));renderSide();}
document.addEventListener('click',e=>{
 const el=e.target.closest('button,[data-go]');if(!el)return;
 if(el.dataset.tab){$('#detail').close();navigate(el.dataset.tab);return;}
 if(el.dataset.go){$('#detail').close();const [tab,section]=el.dataset.go.split('/');navigate(tab,section);return;}
 if(el.dataset.section){navigate(state.tab,el.dataset.section);return;}
 if(el.dataset.filter){state.filter=el.dataset.filter;state.query='';render();document.querySelector(`[data-filter="${state.filter}"]`)?.focus({preventScroll:true});return;}
 if(el.dataset.beer){openBeer(el.dataset.beer);return;}
 if(el.dataset.whisky){openWhisky(el.dataset.whisky);return;}
 if(el.dataset.compare){const id=el.dataset.compare;if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else if(state.compare.length<3)state.compare.push(id);else{toast('한 번에 최대 3종까지 비교할 수 있어요.');return;}renderCompareBar();openBeer(id);return;}
 if(el.dataset.owned){const id=+el.dataset.owned;saved.owned=saved.owned.includes(id)?saved.owned.filter(x=>x!==id):[...saved.owned,id];persist();if(state.tab==='cabinet')render();openWhisky(id);return;}
 if(el.dataset.cask!==undefined){state.cask=+el.dataset.cask;render();return;}
 if(el.dataset.phase!==undefined){state.phase=+el.dataset.phase;render();return;}
 if(el.dataset.answer!==undefined){state.answers[state.quiz]=+el.dataset.answer;render();return;}
 if(el.dataset.noteName){const name=el.dataset.noteName,kind=el.dataset.noteKind;$('#detail').close();navigate('notebook','notes');setTimeout(()=>{if($('#note-name')){$('#note-name').value=name;$('#note-kind').value=kind;$('#note-text').focus();}},50);return;}
 if(el.classList.contains('close')){$('#detail').close();return;}
 switch(el.dataset.action){
 case 'compare-open':openCompare();break;
 case 'compare-clear':state.compare=[];renderCompareBar();break;
 case 'expand-lessons':{const all=[...document.querySelectorAll('#main details.lesson')];const open=all.some(x=>!x.open);all.forEach(d=>d.open=open);el.textContent=open?'모두 접기':'모두 펼치기';break;}
 case 'export':exportData();break;
 case 'quiz-next':state.quiz=(state.quiz+1)%QUIZ.length;render();break;
 }
});
document.addEventListener('input',e=>{
 const el=e.target;
 if(el.dataset.price&&el.value.trim()!==''&&Number.isFinite(Number(el.value))&&Number(el.value)>=0&&Number(el.value)<=10000){saved.prices[el.dataset.price]=Math.round(Number(el.value)*10)/10;persist();updateBudget();}
 if(el.id==='search'){state.query=el.value;$('#results').innerHTML=state.tab==='beer'?beerResults():whiskyResults();updateResultCount();}
 if(el.id==='serve-temp'){const t=+el.value;$('#temp-label').textContent=t+'℃';$('#temp-explain').textContent=t<=5?'보관의 기본 구간. 바로 마시면 일부 향과 풍미가 닫혀 느껴질 수 있습니다.':t<=8?'차가운 라거에서 시작해 조금 더 열린 몰트·홉 향을 관찰하는 구간입니다.':t<=12?'에일과 진한 라거의 몰트·효모 향을 더 볼 수 있는 비교 구간입니다.':'큰 스타우트·배럴 맥주의 향이 더 열릴 수 있습니다. 알코올과 단맛도 함께 커질 수 있어요.';}
});
document.addEventListener('change',async e=>{
 const el=e.target;
 if(el.dataset.price){const n=Number(el.value);if(el.value.trim()===''||!Number.isFinite(n)||n<0||n>10000){toast('0–10,000만 원 사이의 숫자를 입력해주세요.');el.value=price(WHISKIES.find(w=>w.id===+el.dataset.price));return;}saved.prices[el.dataset.price]=Math.round(n*10)/10;persist();updateBudget();}
 if(el.dataset.learn){const id=el.dataset.learn;saved.learned=el.checked?[...new Set([...saved.learned,id])]:saved.learned.filter(x=>x!==id);persist();renderNav();}
 if(el.dataset.ownedCheck){const id=+el.dataset.ownedCheck;saved.owned=el.checked?[...new Set([...saved.owned,id])]:saved.owned.filter(x=>x!==id);persist();}
 if(el.id==='import-file'&&el.files[0]){try{if(el.files[0].size>5000000)throw Error();const data=JSON.parse(await el.files[0].text());if(data.version!==1||!Array.isArray(data.notes))throw Error();const valid=data.notes.filter(n=>n&&['id','name','kind','date','text'].every(k=>typeof n[k]==='string')).map(n=>({id:n.id.slice(0,100),name:n.name.slice(0,160),kind:n.kind.slice(0,30),date:n.date.slice(0,20),batch:String(n.batch||'').slice(0,160),text:n.text.slice(0,10000)}));saved.notes=[...new Map([...saved.notes,...valid].map(n=>[n.id,n])).values()];if(data.prices&&typeof data.prices==='object')for(const w of WHISKIES){const v=data.prices[w.id];if(Number.isFinite(v)&&v>=0&&v<=10000)saved.prices[w.id]=v;}if(Array.isArray(data.owned))saved.owned=[...new Set([...saved.owned,...data.owned.filter(x=>WHISKIES.some(w=>w.id===x))])];if(Array.isArray(data.learned))saved.learned=[...new Set([...saved.learned,...data.learned.filter(x=>[...BEER_LESSONS,...ALL_WHISKY_LESSONS].some(l=>l.id===x))])];persist();render();toast('기록과 계획을 가져왔습니다.');}catch{toast('잔의 지도에서 내보낸 올바른 JSON 파일을 선택해주세요.');}}
});
document.addEventListener('submit',e=>{if(e.target.id!=='note-form')return;e.preventDefault();const f=new FormData(e.target),name=String(f.get('name')).trim(),text=String(f.get('text')).trim();if(!name||!text){toast('제품명과 기록을 입력해주세요.');return;}saved.notes.unshift({id:globalThis.crypto?.randomUUID?.()||String(Date.now()),name,kind:String(f.get('kind')),date:String(f.get('date')),batch:String(f.get('batch')).trim(),text});persist();render();toast('시음 기록을 저장했습니다.');});
$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=$('#detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#detail').close();}});
$('.skip').addEventListener('click',e=>{e.preventDefault();$('#main').focus();$('#main').scrollIntoView();});
